version: "3.9"
services:
  my_frontend:
    build: 
      context: ./
      dockerfile: frontend-Dockerfile
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    environment:
      - CATALOG_HOST=${CATALOG_HOST}
      - CATALOG_PORT=${CATALOG_PORT}
      - ORDER_HOST3=${ORDER_HOST3}
      - ORDER_PORT3=${ORDER_PORT3}
      - ORDER_LEADER_BROADCAST_PORT3=${ORDER_LEADER_BROADCAST_PORT3}
      - ORDER_HEALTH_CHECK_PORT3=${ORDER_HEALTH_CHECK_PORT3}
      - ORDER_HOST2=${ORDER_HOST2}
      - ORDER_PORT2=${ORDER_PORT2}
      - ORDER_LEADER_BROADCAST_PORT2=${ORDER_LEADER_BROADCAST_PORT2}
      - ORDER_HEALTH_CHECK_PORT2=${ORDER_HEALTH_CHECK_PORT2}
      - ORDER_HOST1=${ORDER_HOST1}
      - ORDER_PORT1=${ORDER_PORT1}
      - ORDER_LEADER_BROADCAST_PORT1=${ORDER_LEADER_BROADCAST_PORT1}
      - ORDER_HEALTH_CHECK_PORT1=${ORDER_HEALTH_CHECK_PORT1}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - OUTPUT_DIR=${OUTPUT_DIR}
      - HEALTH_CHECK_INTERVAL=${HEALTH_CHECK_INTERVAL}
      - CACHE_SIZE=${CACHE_SIZE}
      - CACHE_LOG_PATH=${CACHE_LOG_PATH}

  my_order3:
    build: 
      context: ./
      dockerfile: order3-Dockerfile
    volumes:
      - ./data:/data
    environment:
      - CATALOG_HOST=${CATALOG_HOST}
      - CATALOG_PORT=${CATALOG_PORT}
      - ORDER_HOST3=${ORDER_HOST3}
      - ORDER_PORT3=${ORDER_PORT3}
      - ORDER_LEADER_BROADCAST_PORT3=${ORDER_LEADER_BROADCAST_PORT3}
      - ORDER_HEALTH_CHECK_PORT3=${ORDER_HEALTH_CHECK_PORT3}
      - ORDER_HOST2=${ORDER_HOST2}
      - ORDER_PORT2=${ORDER_PORT2}
      - ORDER_LEADER_BROADCAST_PORT2=${ORDER_LEADER_BROADCAST_PORT2}
      - ORDER_HEALTH_CHECK_PORT2=${ORDER_HEALTH_CHECK_PORT2}
      - ORDER_HOST1=${ORDER_HOST1}
      - ORDER_PORT1=${ORDER_PORT1}
      - ORDER_LEADER_BROADCAST_PORT1=${ORDER_LEADER_BROADCAST_PORT1}
      - ORDER_HEALTH_CHECK_PORT1=${ORDER_HEALTH_CHECK_PORT1}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - OUTPUT_DIR=${OUTPUT_DIR}

  my_order2:
    build: 
      context: ./
      dockerfile: order2-Dockerfile
    volumes:
      - ./data:/data
    environment:
      - CATALOG_HOST=${CATALOG_HOST}
      - CATALOG_PORT=${CATALOG_PORT}
      - ORDER_HOST3=${ORDER_HOST3}
      - ORDER_PORT3=${ORDER_PORT3}
      - ORDER_LEADER_BROADCAST_PORT3=${ORDER_LEADER_BROADCAST_PORT3}
      - ORDER_HEALTH_CHECK_PORT3=${ORDER_HEALTH_CHECK_PORT3}
      - ORDER_HOST2=${ORDER_HOST2}
      - ORDER_PORT2=${ORDER_PORT2}
      - ORDER_LEADER_BROADCAST_PORT2=${ORDER_LEADER_BROADCAST_PORT2}
      - ORDER_HEALTH_CHECK_PORT2=${ORDER_HEALTH_CHECK_PORT2}
      - ORDER_HOST1=${ORDER_HOST1}
      - ORDER_PORT1=${ORDER_PORT1}
      - ORDER_LEADER_BROADCAST_PORT1=${ORDER_LEADER_BROADCAST_PORT1}
      - ORDER_HEALTH_CHECK_PORT1=${ORDER_HEALTH_CHECK_PORT1}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - OUTPUT_DIR=${OUTPUT_DIR}

  my_order1:
    build: 
      context: ./
      dockerfile: order1-Dockerfile
    volumes:
      - ./data:/data
    environment:
      - CATALOG_HOST=${CATALOG_HOST}
      - CATALOG_PORT=${CATALOG_PORT}
      - ORDER_HOST3=${ORDER_HOST3}
      - ORDER_PORT3=${ORDER_PORT3}
      - ORDER_LEADER_BROADCAST_PORT3=${ORDER_LEADER_BROADCAST_PORT3}
      - ORDER_HEALTH_CHECK_PORT3=${ORDER_HEALTH_CHECK_PORT3}
      - ORDER_HOST2=${ORDER_HOST2}
      - ORDER_PORT2=${ORDER_PORT2}
      - ORDER_LEADER_BROADCAST_PORT2=${ORDER_LEADER_BROADCAST_PORT2}
      - ORDER_HEALTH_CHECK_PORT2=${ORDER_HEALTH_CHECK_PORT2}
      - ORDER_HOST1=${ORDER_HOST1}
      - ORDER_PORT1=${ORDER_PORT1}
      - ORDER_LEADER_BROADCAST_PORT1=${ORDER_LEADER_BROADCAST_PORT1}
      - ORDER_HEALTH_CHECK_PORT1=${ORDER_HEALTH_CHECK_PORT1}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - OUTPUT_DIR=${OUTPUT_DIR}

  my_catalog:
    build: 
      context: ./
      dockerfile: catalog-Dockerfile
    volumes:
      - ./data:/data
    environment:
      - CATALOG_HOST=${CATALOG_HOST}
      - CATALOG_PORT=${CATALOG_PORT}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - OUTPUT_DIR=${OUTPUT_DIR}

